eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://#####:5555/eureka/
  instance:
    prefer-ip-address: true
#spring:
#  datasource:
#    url: jdbc:mysql://#####:3306/KnowledgeGraph?serverTimezone=CTT&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    max-active: 200
#    max-idle: 20
#    min-idle: 10
spring:
  neo4j:
    uri: bolt://####:7687
    authentication:
      username: neo4j
      password: 123456
