FROM openjdk:8u262-jre-slim-buster
ADD ./user/target/user-0.0.1-SNAPSHOT.jar /testname-coin/testname-user.jar
ADD runboot-user.sh testname-coin/
WORKDIR /testname-coin/
RUN chmod a+x runboot-user.sh
CMD /testname-coin/runboot-user.sh