
spring:
  neo4j:
#    uri: bolt://####:7687
    uri: bolt://####:7687
    authentication:
      username: neo4j
      password: ####
eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://#####:5555/eureka/
  instance:
    prefer-ip-address: true
