server:
  port: 7001

spring:
  application:
    name:
      coin-so
  profiles:
    active: prod

  data:
    mongodb:
      host: ######
      port: 27017
      database: scrapy
      username: scrapy
      password: testname123456
      authentication-database: scrapy
