
spring:
  neo4j:
    uri: bolt://121.5.118.248:7687
#    uri: bolt://106.15.93.81:7687
    authentication:
      username: neo4j
      password: root
eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://121.5.118.248:5555/eureka/
  instance:
    prefer-ip-address: true
