spring:
  neo4j:
    uri: bolt://106.15.93.81:7687
    authentication:
      username: neo4j
      password: 123456
  data:
    mongodb:
      host: 106.15.93.81
      port: 27017
      database: scrapy
      username: scrapy
      password: testname123456


eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://localhost:5555/eureka/
  instance:
    prefer-ip-address: true
