spring:
  neo4j:
    uri: bolt://####:7687
    authentication:
      username: ###
      password: ###
  data:
    mongodb:
      host: ###
      port: 27017
      database: scrapy
      username: scrapy
      password: testname123456
      authentication-database: scrapy


eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://localhost:5555/eureka/
  instance:
    prefer-ip-address: true
